### ISSUE TITLE
Add a CMake install target

### ISSUE THREAD

**Issue by cjdb** [tzlaine/text#184]
It'd be great to add this library to package managers, but that will require install targets to be generated.

**Comment by tzlaine** [comment]
Sorry it took me so long to see this.  I'll get on this right away.  You just need the typical install arrangement, right?  A root directory `ROOT` that the user provides , with this layout:

`ROOT/include`
`ROOT/lib`

... right?

**Comment by cjdb** [comment]
Pretty much. I'd have contributed it myself, but I never seem to get CMake install targets right.

**Comment by tzlaine** [comment]
Ok, this is "done", in that there is an install target.  It just installs the lib binary and the headers.  I have no idea how to do it the proper way, with the CMake targets and config files.  The problem is that text depends on Boost, but is not yet a part of Boost.  It uses Boost via FindBoost when it can, and otherwise it clones the bits of Boost it needs.  In either case, there is a boost lib that text depends on.  I cannot export text without its dependency boost, as far as I can tell.  If someone can explain to me how this is supposed to work, I can change this.

**Comment by tzlaine** [comment]
@cjdb Ok, I figured out a way to export the .cmake files for targets and config as part of the install target.  There is still a dependency on boost, but its implicit when using those files.  Users can do:

`find_package(text PATHS <path-to-installed-text>)`

And then later:

`target_link_libraries(my_target Boost::text ...)`

But the "..." needs to include "Boost::boost", or whatever the main Boost dependency is called.  Hope that helps.

**Comment by cjdb** [comment]
That looks great, thanks @tzlaine! I'll make a vcpkg submission and then come back with a PR for your readme (if you want to advertise it's available on vcpkg).
